MyProjects/Application2016/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Application2016.Models
{
    public class LoginModel:BaseModel
    {
        [Required(ErrorMessage = "Xin hãy nhập tên / Email")]
        [Display(Name = "User name")]
        public string Username_Model { get; set; }

        [Required(ErrorMessage = "Xin hãy nhập mật khẩu")]
        [Display(Name = "Password")]
        public string Password_Model { get; set; }

        [Required]
        [Display(Name = "Remember?")]
        public bool Remember_Model { get; set; }
    }
}

MyProjects/Application2016/Areas/Admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Application2016.Areas.Admin.Models;
using BusinessLayer;
using Application2016.Helpers;

namespace Application2016.Areas.Admin.Controllers
{
    public class ArticleController : BaseController
    {
        public ArticleController()
        {
            ViewBag.ActionMenu = "AdminSetting";
            ViewBag.ActionSubMenu = "Article";
        }

        ArticleService _service = new ArticleService();
        //
        // GET: /Admin/Article/
        [HttpGet]
        public ActionResult Index(ArticleCondition Condition)
        {
            ListArticleModel model = new ListArticleModel();
            CategoryService service = new CategoryService();

            model.Condition = Condition;
            model.ListCategory = service.ListItem();
            model.ListCategory.Insert(0, new Entities.Item() { Text = "Chọn thư mục", Id = 0 });
            int total = 0;
            try
            {
                model.ListArticle = _service.List(Condition.CatId, Condition.SearchText, Condition.DisplayOnly, Condition.Page, Condition.PageSize, out total);
            }
            catch (Exception ex)
            {
                Logs.LogWrite(ex.ToString());
            }
            Paging(Condition.Page, total);

            return View(model);
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            ArticleModel model = new ArticleModel();
            if (Id <= 0)
            {
                model.Article = new Entities.Article();
                model.Article.Display = true;
            }
            else
            {
                model.Article = _service.GetById(Id);
            }
            model.ListCategory = _service.ListCategory();

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Update(ArticleModel model)
        {
            if (ModelState.IsValid)
            {
                model.Article.Alias = string.IsNullOrEmpty(model.Article.Alias)? model.Article.Title.ToAlias(): model.Article.Alias.ToAlias();
                int result = _service.Save(model.Article);
                if (result > 0)
                {
                    TempData[AdminConfigs.TEMP_MESSAGE] = AdminConfigs.MESSAGE_UPDATE_SUCCESS;
                    TempData[AdminConfigs.TEMP_REDIRECT] = @Url.Action("Index", "Article");
                }
                else
                {
                    TempData[AdminConfigs.TEMP_MESSAGE] = AdminConfigs.MESSAGE_UPDATE_ERROR;
                }
            }
            model.ListCategory = _service.ListCategory();
            return View(model);
        }
    }
}

MyProjects/Application2016/Areas/Admin/Controllers/BoxLinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Application2016.Areas.Admin.Models;
using BusinessLayer;

namespace Application2016.Areas.Admin.Controllers
{
    public class BoxLinkController : BaseController
    {
        BoxLinkService _service = new BoxLinkService();

        public BoxLinkController()
        {
            ViewBag.ActionMenu = "BoxLink";
            ViewBag.ActionSubMenu = "BoxLink";
        }

        public ActionResult Index()
        {
            ListBoxLinkModel model = new ListBoxLinkModel();
            model.ListBoxLink = _service.List();

            return View(model);
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            BoxLinkModel model = new BoxLinkModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(BoxLinkModel model)
        {
            return View(model);
        }
    }
}

MyProjects/Application2016/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Application2016.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: /Article/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }

    }
}

MyProjects/Application2016/Controllers/Template1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Application2016.Models;
using BusinessLayer;
using Application2016.Helpers;
using CaptchaMvc.HtmlHelpers;
using BusinessLayer.Helpers;
using Entities;
using Application2016.Enums;

namespace Application2016.Controllers
{
    public class Template1Controller : BaseController
    {
        ProductService productService = new ProductService();
        UserService userService = new UserService();

        public ActionResult Index(Template1SearchModel model)
        {
            GetDataModel(model);

            // Get Tab ID
            int tabId = 0;
            switch (model.TransactionType)
            {
                case 0:
                    tabId = 0;
                    break;
                case 1:
                    tabId = 1;
                    break;
                case 2:
                    tabId = 2;
                    break;
                case 3:
                    break;
                default:
                    tabId = 0;
                    break;
            }
            Entities.ProductCondtions e = new Entities.ProductCondtions();
            model.Mapping(model, ref e);
            var lstTemp = productService.List(e);

            // Lấy danh sách Product Follow
            int loginUser = 0;
            int.TryParse(CookieHelper.Get(AdminConfigs.COOKIES_USER_ID), out loginUser);
            if(loginUser>0){
                var productFollows = productService.ListProductFollowId(loginUser);
                if (productFollows!=null && productFollows.Count > 0)
                {
                    foreach (var item in productFollows)
                    {
                        lstTemp.Where(x => x.Id == item.ProductId).Select(y => { y.IsFollow = item.IsFollow; return y; }).ToList();
                    }
                }
            }

            int totalRecord = 0;
            if (lstTemp.Count > 0)
            {
                totalRecord = lstTemp[0].Total.Value;
                Paging(model.Page, totalRecord, model.PageSize);
            }

            ViewBag.BoxTitle = "Danh sách nhà";
            ViewBag.ListProduct = lstTemp;
            ViewBag.TabID = tabId;

            return View(model);
        }

        public ActionResult Template1ProductFeature()
        {
            var lstTemp = productService.List();

            // Lấy danh sách Product Follow
            int loginUser = 0;
            int.TryParse(CookieHelper.Get(AdminConfigs.COOKIES_USER_ID), out loginUser);
            if (loginUser > 0)
            {
                var productFollows = productService.ListProductFollowId(loginUser);
                if (productFollows != null && productFollows.Count > 0)
                {
                    foreach (var item in productFollows)
                    {
                        lstTemp.Where(x => x.Id == item.ProductId).Select(y => { y.IsFollow = item.IsFollow; return y; }).ToList();
                    }
                }
            }

            ViewBag.ListProduct = lstTemp;
            ViewBag.BoxTitle = "Danh sách nhà gợi ý";
            return PartialView("_ListItem");
        }

        /// <summary>
        /// Danh sách sản phẩm gợi ý.
        /// </summary>
        /// <param name="withOutId"></param>
        /// <param name="cityId"></param>
        /// <param name="districtId"></param>
        /// <returns></returns>
        public ActionResult Template1ProductSuggest(int withOutId, int cityId, int districtId)
        {
            Entities.ProductCondtions condition = new Entities.ProductCondtions();
            condition.withOutId = withOutId;
            condition.City = cityId;
            condition.District = districtId;
            condition.Page = 1;
            condition.Limit = 20;
            var listProduct = productService.List(condition);

            ViewBag.ListProduct = listProduct;
            ViewBag.BoxTitle = "Danh sách nhà gợi ý";
            return PartialView("_ListItem");
        }

        public ActionResult ProductNew()
        {
            var lstTemp = productService.List();
            ViewBag.ListProduct = lstTemp;
            return PartialView("_BoxProductVertical");
        }

        public ActionResult Detail(int id)
        {
            ProductService _service = new ProductService();
            Entities.Product product = _service.GetById(id);
            ProductModel model = new ProductModel();
            model.ListImage = new List<Entities.ProductImage>();
            if (product != null)
            {
                // Lấy thông tin sản phẩm.
                model.MapFrom(product, ref model);

                // Lấy thông tin kiểu nhà.
                var listProductType = _service.ListProductType();
                model.ProductTypeText = (from p in listProductType
                                         where p.Id == model.Product_Type
                                         select p.Text).FirstOrDefault();

                // Lấy thông tin người đăng.
                UserService _userService = new UserService();
                var user = _userService.GetById(model.UserId);
                model.Username = user.UserName;
                model.PhoneNumber = user.Phone;

                // Lấy danh sách ảnh sản phẩm.
                model.ListImage = _service.GetListImage(id);

                // Kiểm tra có phải là người post hay không.
                if (CookieHelper.Get(AdminConfigs.COOKIES_USER_ID) != null)
                {
                    if (CookieHelper.Get(AdminConfigs.COOKIES_USER_ID) == model.UserId.ToString())
                    {
                        model.IsPoster = true;
                    }
                    else
                    {
                        model.IsPoster = false;
                    }
                }

                // Lấy thông tin điều chỉnh giá.
                model.NewCost = _service.GetCostChangeByOwn(id, product.UserId);

                // Lấy danh sách giá đặt mua
                List<Entities.Product_ChangeCost> lstChangeCost = _service.GetListProductChangeCost(id, product.UserId);
                model.ListChangeCost = lstChangeCost;

            }
            else
            {
                model.ListChangeCost = new List<Entities.Product_ChangeCost>();
            }
            return View(model);
        }

        public void GetDataModel(Template1SearchModel model)
        {
            // Lấy danh sách các kiểu nhà.
            ProductService _productService = new ProductService();
            ViewBag.ListProductType = _productService.ListProductType();

            // Lấy danh sách các tỉnh.
            PlaceService _placeService = new PlaceService();
            ViewBag.ListCity = _placeService.ListPlaceItemByParent(0);
            ViewBag.ListCity.Insert(0, new Entities.Item() { Text = "--- Chọn tỉnh ---", Id = -1 });
            // Lấy danh sách các huyện quận theo tỉnh.
            if (model.CityId > 0)
            {
                ViewBag.ListDistrict = _placeService.ListPlaceItemByParent(model.CityId);
            }
            else
            {
                ViewBag.ListDistrict = new List<Entities.Item>();
            }
            ViewBag.ListDistrict.Insert(0, new Entities.Item() { Text = "--- Chọn quận huyện ---", Id = -1 });

            // Lấy danh sách xã phường theo quận huyện.
            if (model.DistrictId > 0)
            {
                ViewBag.ListWard = _placeService.ListPlaceItemByParent(model.DistrictId);
            }
            else
            {
                ViewBag.ListWard = new List<Entities.Item>();
            }
            ViewBag.ListWard.Insert(0, new Entities.Item() { Text = "--- Chọn xã phường ---", Id = -1 });

            // Lấy danh sách diện tích nhỏ nhất
            var listAreaMin = Helpers.DefaultData.ListArea();

            // Lấy danh sách diện tích nhỏ nhất
            var listAreaMax = Helpers.DefaultData.ListArea();
            listAreaMax.Add(new Entities.Item()
            {
                Id = 100000,
                Text = ">"+listAreaMin[listAreaMin.Count -1].Id.ToString()
            });


            if (model.MaxArea > 0)
            {
                listAreaMin = listAreaMin.Where(x => x.Id <= model.MaxArea).ToList();

            }

            if (model.MinArea > 0)
            {
                listAreaMax = listAreaMax.Where(x => x.Id >= model.MinArea).ToList();
            }


            ViewBag.ListAreaMin = listAreaMin;

            ViewBag.ListAreaMax = listAreaMax;

            model.ListUser = userService.ListItem();
        }

        public ActionResult BoxLink(int Position)
        {
            ArticleService articleService = new ArticleService();

            var ListArticle = articleService.List(0);

            ViewBag.ListArticle = ListArticle;

            ViewBag.WebsiteInfo = HttpContext.Application[AdminConfigs.SETTING_WEBSITE];

            ViewBag.Social = HttpContext.Application[AdminConfigs.SETTING_SOCIAL_NETWORK];

            return PartialView("BoxLink");
        }

        public ActionResult Article(int Id)
        {
            ArticleService articleService = new ArticleService();
            ArticleModel model = new ArticleModel();
            model.Article = articleService.GetById(Id);

            return View(model);
        }

        public ActionResult GetMessage()
        {
            string strUserId = CookieHelper.Get(AdminConfigs.COOKIES_USER_ID);
            if (strUserId != null)
            {
                // Lấy thông tin host.
                Uri uri = Request.Url;
                string urlHost = uri.GetLeftPart(UriPartial.Authority);
                var listMessage = productService.ListMessage(int.Parse(strUserId));
                if (listMessage.Count > 0)
                {
                    foreach (var product in listMessage)
                    {

MyProjects/Application2016/Views/Template1/404.cshtml
@{
    ViewBag.Title = "404";
    Layout = "~/Views/Shared/_LayoutTemplate1.cshtml";
}

@section MainContent{
<h2>404</h2>

}

MyProjects/Application2016/Views/Template1/Article.cshtml
@model Application2016.Models.ArticleModel
@{
    ViewBag.Title = "Article";
    Layout = "~/Views/Shared/_LayoutTemplate1.cshtml";
}

<h2>Article</h2>
@section MainContent{
    <div class="col-xs-12 col-sm-2">
        @Html.Action("ProductNew", "Template1")
    </div>
    <div class="col-xs-12 col-sm-10">        
        @Html.Raw(Model.Article.Body)
    </div>

}

MyProjects/Application2016/Views/Template1/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutTemplate1.cshtml";
}
@section MainContent{
    <div class="col-xs-12 col-sm-2">
        @Html.Action("ProductNew", "Template1")
    </div>
    <div class="col-xs-12 col-sm-10">
        <form id="id-message-form" class=" form-horizontal message-form col-xs-12">
        <div id="id-message-new-navbar" class="message-navbar clearfix">
            <div class="message-bar">
                <div class="message-toolbar">
                    <button type="button" class="btn btn-xs btn-white btn-primary">
                        <i class="ace-icon fa fa-floppy-o bigger-125"></i><span class="bigger-110">Save Draft</span>
                    </button>
                    <button type="button" class="btn btn-xs btn-white btn-primary">
                        <i class="ace-icon fa fa-times bigger-125 orange2"></i><span class="bigger-110">Discard</span>
                    </button>
                </div>
            </div>
            <div>
                <div class="messagebar-item-left">
                    <a href="#" class="btn-back-message-list"><i class="ace-icon fa fa-arrow-left bigger-110 middle blue">
                    </i><b class="middle bigger-110">Back</b> </a>
                </div>
                <div class="messagebar-item-right">
                    <span class="inline btn-send-message">
                        <button type="button" class="btn btn-sm btn-primary no-border btn-white btn-round">
                            <span class="bigger-110">Send</span> <i class="ace-icon fa fa-arrow-right icon-on-right">
                            </i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-recipient">
                    Người nhận:</label>
                <div class="col-sm-9">
                    <span class="input-icon">
                        <input type="email" name="recipient" id="form-field-recipient" data-value="alex@doe.com"
                            value="" placeholder="test@gmail.com" />
                        <i class="ace-icon fa fa-user"></i></span>
                </div>
            </div>
            <div class="hr hr-18 dotted">
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-subject">
                    Chủ đề:</label>
                <div class="col-sm-6 col-xs-12">
                    <div class="input-icon block col-xs-12 no-padding">
                        <input maxlength="100" type="text" class="col-xs-12" name="subject" id="form-field-subject"
                            placeholder="Subject" />
                        <i class="ace-icon fa fa-comment-o"></i>
                    </div>
                </div>
            </div>
            <div class="hr hr-18 dotted">
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">
                    <span class="inline space-24 hidden-480"></span>Nội dung:
                </label>
                <div class="col-sm-9">
                    <div class="wysiwyg-editor">
                    </div>
                </div>
            </div>
            <div class="hr hr-18 dotted">
            </div>
            <div class="form-group no-margin-bottom">
                <label class="col-sm-3 control-label no-padding-right">
                    File đính kèm:</label>
                <div class="col-sm-9">
                    <div id="form-attachments">
                        <input type="file" name="attachment[]" />
                    </div>
                </div>
            </div>
            <div class="align-right">
                <button id="id-add-attachment" type="button" class="btn btn-sm btn-danger">
                    <i class="ace-icon fa fa-paperclip bigger-140"></i>Thêm file đính kèm
                </button>
            </div>
            <div class="space">
            </div>
        </div>
        </form>
    </div>
    <script src="../../Assets/Template1/js/bootstrap-wysiwyg.min.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(function ($) {
//        Inbox.show_form();

        Inbox.show_form = function () {
            if ($('.message-form').is(':visible')) return;
            if (!form_initialized) {
                initialize_form();
            }


            var message = $('.message-list');
            $('.message-container').append('<div class="message-loading-overlay"><i class="fa-spin ace-icon fa fa-spinner orange2 bigger-160"></i></div>');

            setTimeout(function () {
                message.next().addClass('hide');

                $('.message-container').find('.message-loading-overlay').remove();

                $('.message-list').addClass('hide');
                $('.message-footer').addClass('hide');
                $('.message-form').removeClass('hide').insertAfter('.message-list');

                $('.message-navbar').addClass('hide');
                $('#id-message-new-navbar').removeClass('hide');


                //reset form??
                $('.message-form .wysiwyg-editor').empty();

                $('.message-form .ace-file-input').closest('.file-input-container:not(:first-child)').remove();
                $('.message-form input[type=file]').ace_file_input('reset_input');

                $('.message-form').get(0).reset();

            }, 300 + parseInt(Math.random() * 300));
        }

        function initialize_form() {
            if (form_initialized) return;
            form_initialized = true;

            //intialize wysiwyg editor
            $('.message-form .wysiwyg-editor').ace_wysiwyg({
                toolbar:
						[
							'bold',
							'italic',
							'strikethrough',
							'underline',
							null,
							'justifyleft',
							'justifycenter',
							'justifyright',
							null,
							'createLink',
							'unlink',
							null,
							'undo',
							'redo'
						]
            }).prev().addClass('wysiwyg-style1');



            //file input
            $('.message-form input[type=file]').ace_file_input()
					.closest('.ace-file-input')
					.addClass('width-90 inline')
					.wrap('<div class="form-group file-input-container"><div class="col-sm-7"></div></div>');

            //Add Attachment
            //the button to add a new file input
            $('#id-add-attachment')
					.on('click', function () {
					    var file = $('<input type="file" name="attachment[]" />').appendTo('#form-attachments');
					    file.ace_file_input();

					    file.closest('.ace-file-input')
						.addClass('width-90 inline')
						.wrap('<div class="form-group file-input-container"><div class="col-sm-7"></div></div>')
						.parent().append('<div class="action-buttons pull-right col-xs-1">\
							<a href="#" data-action="delete" class="middle">\
								<i class="ace-icon fa fa-trash-o red bigger-130 middle"></i>\
							</a>\
						</div>')
						.find('a[data-action=delete]').on('click', function (e) {
						    //the button that removes the newly inserted file input
						    e.preventDefault();
						    $(this).closest('.file-input-container').hide(300, function () { $(this).remove() });
						});
					});
        } //initialize_form

        $('#id-add-attachment')
		    .on('click', function () {
			    var file = $('<input type="file" name="attachment[]" />').appendTo('#form-attachments');
			    file.ace_file_input();

			    file.closest('.ace-file-input')
			    .addClass('width-90 inline')
			    .wrap('<div class="form-group file-input-container"><div class="col-sm-7"></div></div>')
			    .parent().append('<div class="action-buttons pull-right col-xs-1">\
				    <a href="#" data-action="delete" class="middle">\
					    <i class="ace-icon fa fa-trash-o red bigger-130 middle"></i>\
				    </a>\
			    </div>')
			    .find('a[data-action=delete]').on('click', function (e) {
				    //the button that removes the newly inserted file input
				    e.preventDefault();
				    $(this).closest('.file-input-container').hide(300, function () { $(this).remove() });
			    });
		    });
    });
</script>
}

MyProjects/Application2016/Views/Template1/Login_Model.cshtml
@model Application2016.Models.LoginModel
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h4 class="header blue lighter bigger">
                <i class="ace-icon fa fa-coffee green"></i>Tài khoản của bạn
            </h4>
            <div class="space-6">
            </div>
            @using (Ajax.BeginForm("Login", "Template1", FormMethod.Post,
                            new AjaxOptions
                            {
                                InsertionMode = InsertionMode.Replace,
                                HttpMethod = "POST"
                            }))
                {
                @Html.AntiForgeryToken()
                <fieldset>
                    <label class="block clearfix">
                        <span class="block input-icon input-icon-right">
                            @Html.TextBoxFor(m => m.Username_Model, new { @class = "form-control", @placeholder = "Email hoặc Username" })
                            @Html.ValidationMessageFor(m => m.Username_Model)
                            <i class="ace-icon fa fa-user"></i></span>
                    </label>
                    <label class="block clearfix">
                        <span class="block input-icon input-icon-right">
                            @Html.TextBoxFor(m => m.Password_Model, new { @class = "form-control", @placeholder = "Mật khẩu", @type="password" })
                            @Html.ValidationMessageFor(m => m.Password_Model)
                            <i class="ace-icon fa fa-lock"></i></span>
                    </label>
                    <div class="space">
                    </div>
                    <div class="">
                        <label class="">
                            @Html.EditorFor(m => m.Remember_Model, new { @class = "ace" })
                            <span class="lbl">Ghi nhớ</span>
                        </label>
                        <button type="button" id="btnDoLogin" class="width-35 pull-right btn btn-sm btn-primary">
                            <i class="ace-icon fa fa-key"></i><span class="bigger-110">Đăng nhập</span>
                        </button>
                    </div>
                    <div class="space-4">
                    </div>
                </fieldset>
            }
        </div>
        <!-- /.widget-main -->
        <div class="toolbar clearfix">
            <div>
                <a href="@Url.Action("ForgotPassword", "User", new { area = "Admin" })" data-target="#forgot-box" class="forgot-password-link">
                    <i class="ace-icon fa fa-arrow-left"></i>Quên mật khẩu </a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var message = '@Html.Raw(Model.Message)';
    var result = '@Model.Result';
    if (result == '1') {
        if (message.length > 0) {
            alert(message);
        }
        $('#register_model').modal('hide');
        location.reload(false)
    } else if (result < 0) {
        alert(message);
    }

    $('#btnDoLogin').on('click', function () {
        var self = $(this);
        $.ajax({
            url: '@Url.Action("Login", "Template1")',
            type: 'POST',
            async: false,
            data: self.closest('form').serialize(),
            success: function (data) {
                var message = '@Html.Raw(Model.Message)';
                var result = '@Model.Result';
                if (result == '1') {
                    if (message.length > 0) {
                        alert(message);
                    }
                    $('#register_model').modal('hide');
                    location.reload(false)
                } else {
                    if (result == '0' && message.length > 0) {
                        alert(message);
                    }
                    $('#register_model').html(data);
                }
            }
        });
    });
</script>

MyProjects/Application2016/Views/Template1/_BoxCommonInfo.cshtml
@{
    ViewBag.Title = "_BoxCommonInfo";
}

<h2>_BoxCommonInfo</h2>

MyProjects/Application2016/Views/Template1/_BoxProductVertical.cshtml
@using Application2016.Helpers;
@using Application2016.Enums;
@{
    var ListProduct = ViewBag.ListProduct as IList<Entities.Product>;
}
<style type="text/css">
    li .product-vertical
    {
        height: 120px;
        width: 100%;
    }
</style>
<div class="list-wrpaaer" style="height:480px; background-color: #ecf1f4;">
    <ul id="marquee-vertical">
     @foreach (var item in ViewBag.ListProduct as IList<Entities.Product>)
     {
         string image = "no avatar";
         if (item.Avatar != null && item.Avatar != "" && item.Avatar_Url != null)
         {
             image = Url.Content(item.Avatar_Url + item.Avatar);
         }
         else
         {
             image = Url.Content("~/Assets/Images/home-default.png");
         }
         <li class="product-vertical">
            <div style="border: solid 1px #fff;">
                <a href="../@AdminConfigs.FRIENDLY_LINK_PRODUCT_DETAIL.ToFriendlyUrl(item.Id, item.Text_Alias)">
                   <img class="media-object" height="100" src="@image" data-src="holder.js/72x72" alt="@item.Text" />
                </a>
                <p>
                    @item.Text
                </p>
            </div>
         </li>
     }
    </ul>
</div>


<script src="@Url.Content("~/Assets/js/jquery.marquee.js")" type="text/javascript"></script>
<script type="text/javascript">
    $('#marquee-vertical').marquee();  
</script>